site_name: docs.instructlab.ai
site_url: https://docs.instructlab.ai

# Repository
repo_name: docs.instructlab.ai
repo_url: https://github.com/instructlab/docs.instructlab.ai
edit_uri: edit/main/docs

# Navigation
nav:
  - Welcome:
      - About InstructLab: index.md
  - Getting Started:
      - Mac Metal: getting-started/mac_metal.md
      - Linux NVIDIA: getting-started/linux_nvidia.md
      - Linux AMD: getting-started/linux_amd.md
      - Creating New Knowledge or Skills: getting-started/creating_new_knowledge_or_skills.md
  - Community:
      - Code of Conduct: community/CODE_OF_CONDUCT.md
      - Code of Conduct Committee: community/CODE_OF_CONDUCT_COMMITTEE.md
      - FAQ: community/FAQ.md
      - Governce Policy: community/GOVERNANCE.md
      - Slack Guide: community/InstructLab_SLACK_GUIDE.md
      - Slack Moderation Guide: community/InstructLab_SLACK_MODERATION_GUIDE.md
  - Taxonomy:
      - About Taxonomy: taxonomy/index.md
      - qna.yaml Best Practices: taxonomy/qna_yaml_best_practices.md
      - Skills Overview: taxonomy/skills/index.md
      - Skills Guide: taxonomy/skills/skills_guide.md
      - Knowledge Overview: taxonomy/knowledge/index.md
      - Knowledge Guide: taxonomy/knowledge/guide.md
      - Knowledge Contribution Details: taxonomy/knowledge/contribution_details.md
  - Community Model Build:
      - About Community Model Build: cmb/index.md
  - References:
      - Additional Resources: resources/RESOURCES.md
      - Contributors: resources/CONTRIBUTORS.md
      - MkDocs Cheatsheet: resources/MKDOCS.md

## YOU SHOULD NOT NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2024- Red Hat Inc.

theme:
  name: material
  icon:
    logo: material/library
  logo: images/ilab_dog.png
  palette:
    scheme: default
    primary:
      primary: custom
    accent: purple

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
